# This is a basic workflow to help you get started with Actions

name: UKGOV-PaaS-Deployment-SANDBOX

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ actions-poc ]
  pull_request:
    branches: [ actions-poc ]

env:
  APP_ENV: 'sandbox'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: [self-hosted, Linux, X64]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # - name: Install cf-cli
    #   run: |
    #     sudo apt-get install -y wget gnupg2
    #     sudo wget -q -O - https://packages.cloudfoundry.org/debian/cli.cloudfoundry.org.key | sudo apt-key add -
    #     echo "deb https://packages.cloudfoundry.org/debian stable main" | sudo tee /etc/apt/sources.list.d/cloudfoundry-cli.list
    #     sudo apt-get update
    #     sudo apt-get install -y cf-cli
    #

    - name: Login to CF endpoint
      run: cf login -a ${{ secrets.CF_API }} -u ${{ secrets.CF_USER }} -p ${{ secrets.CF_PASSWORD }} -o ${{ secrets.CF_ORG }} -s ${{ env.APP_ENV }}

    - name: Create APP
      run: cf v3-create-app ${{ secrets.APP_NAME }}-${{ env.APP_ENV }}

    - name: Set CF Env
      run: |
        cf set-env '${{ secrets.APP_NAME }}-${{ env.APP_ENV }}' ALLOWED_HOSTS '${{ secrets.ALLOWED_HOSTS }}'
        cf set-env '${{ secrets.APP_NAME }}-${{ env.APP_ENV }}' SECRET_KEY '${{ secrets.DJANGO_SECRET }}'
        cf set-env '${{ secrets.APP_NAME }}-${{ env.APP_ENV }}' DISABLE_COLLECTSTATIC 1

    - name: Deploy app
      run: cf push '${{ secrets.APP_NAME }}-${{ env.APP_ENV }}' -b python_buildpack
