# This is a basic workflow to help you get started with Actions

name: UKGOV-PaaS-Deployment-SANDBOX

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ actions-poc ]
  pull_request:
    branches: [ actions-poc ]

env:
  GITHUB_REPOSITORY: "lite-document-store"
  PAAS_ENV: "dev"
  PAAS_NAMESPACE: "webops"
  PAAS_APP_NAME:  "lite-document-store"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: [self-hosted, Linux, X64]

    # Steps represent a sequence of tasks that will be executed as part of the job.
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it.
    - uses: actions/checkout@v2

    - name: Set CF env VARs from CI Vault
      run: python3 /home/github/vault.py

    #This can all be moved into the vauly/py scripts, no need to do this here.
    - name: Login to CF endpoint
      run: cf login -a $CF_DOMAIN -u $CF_USERNAME -p $CF_PASSWORD -o $CF_ORG -s '${{ env.PAAS_NAMESPACE }}-${{ env.PAAS_ENV }}'

    - name: Create APP
      run: cf v3-create-app '${{ env.PAAS_APP_NAME }}-${{ env.PAAS_ENV }}'

    - name: Deploy APP
      run: cf push '${{ env.PAAS_APP_NAME }}-${{ env.PAAS_ENV }}' -b python_buildpack
