# This is a basic workflow to help you get started with Actions

name: UKGOV-PaaS-Deployment-SANDBOX

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ actions-poc ]
  pull_request:
    branches: [ actions-poc ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: [self-hosted, Linux, X64]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Set CF env VARs from CI Vault
      run: python3 /home/github/vault.py
      env:
        VAULT_URL: ${{ secrets.VAULT_URL }}
        VAULT_TOKEN: ${{ secrets.VAULT_TOKEN }}
        CF_USERNAME: ${{ secrets.CF_USERNAME }}
        CF_PASSWORD: ${{ secrets.CF_PASSWORD }}
        CF_DOMAIN: ${{ secrets.CF_DOMAIN }}
        PAAS_ENV: ${{ secrets.PAAS_ENV }}
        PAAS_NAMESPACE: ${{ secrets.PAAS_NAMESPACE }}
        PAAS_APP_NAME:  ${{ secrets.PAAS_APP_NAME }}

    - name: Login to CF endpoint
      run: cf login -a ${{ secrets.CF_DOMAIN }} -u ${{ secrets.CF_USERNAME }} -p ${{ secrets.CF_PASSWORD }} -o ${{ secrets.CF_ORG }} -s ${{ secrets.PAAS_NAMESPACE }}-${{ secrets.PAAS_ENV }}

    - name: Create APP
      run: cf v3-create-app ${{ secrets.PAAS_APP_NAME }}-${{ secrets.PAAS_ENV }}

    - name: Deploy APP
      run: cf push '${{ secrets.PAAS_APP_NAME }}-${{ secrets.PAAS_ENV }}' -b python_buildpack
